library:
  source-dirs: src
  dependencies:
  - ansi-wl-pprint
  - optparse-applicative
  - directory
  - transformers
  - safe-exceptions
  - regex-applicative
  - filepath
  - split
  ghc-options:
  - -Wunused-imports
tests:
  slurm-utils-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - slurm-utils
copyright: (c) Bob Zimmermann
maintainer: robert.zimmermann@univie.ac.at
dependencies:
- optparse-applicative
- base >= 4.7 && < 5
name: slurm-utils
version: 0.2.5.2
extra-source-files:
- README.md
- ChangeLog.md
author: Bob Zimmermann
github: nijibabulu/slurm-utils
license: BSD3
executables:
  tmprewrite:
    source-dirs: tmprewrite
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wunused-imports
    dependencies:
    - slurm-utils
  slurmtasks:
    source-dirs: slurmtasks
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wunused-imports
    dependencies:
    - slurm-utils
    - optparse-applicative
    - filepath
    - text
description: Please see the README on GitHub at <https://github.com/nijibabulu/slurm-utils#readme>
